import json
import logging
from typing import List, Dict, Any

# Configure basic logging.
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def generate_llm_response(prompt: str) -> str:
    """
    Mock function to simulate an LLM call. 
    In a real scenario, this would use OpenAI, Gemini, or a local model.
    """
    # Simulating an LLM returning a JSON string.
    return '''{"restaurant_name": "Luigi's Trattoria", "cuisine": "Italian", "rating": 4.8, "reviews_summary": "Excellent pasta and cozy atmosphere."}'''

def validate_restaurant_json(json_string: str) -> Dict[str, Any]:
    """
    Validates that the LLM output is valid JSON and contains required keys.
    """
    try:
        # 1.
        data = json.loads(json_string)
        
        # 2.
        required_keys = {"restaurant_name", "cuisine", "rating"}
        if not required_keys.issubset(data.keys()):
            raise ValueError(f"Missing required keys. Expected {required_keys}")
            
        return data
        
    except json.JSONDecodeError as e:
        logging.error(f"Invalid JSON generated by LLM: {e}")
        return None
    except ValueError as e:
        logging.error(f"Schema validation failed: {e}")
        return None

def process_unstructured_restaurant_data(unstructured_data_list: List[str]) -> List[Dict[str, Any]]:
    """
    The main loop to generate and validate JSON outputs for each restaurant.
    """
    processed_restaurants = []
    
    # =====================================================================.
    # LOOP TO GENERATE AND VALIDATE JSON OUTPUTS FOR EACH RESTAURANT.
    # =====================================================================.
    for i, raw_text in enumerate(unstructured_data_list):
        logging.info(f"--- Processing Restaurant {i+1} ---")
        
        # Step 1: Construct the prompt for the LLM.
        prompt = (
            "Extract the restaurant name, cuisine type, rating, and a brief "
            f"review summary from the following text. Return ONLY valid JSON: {raw_text}"
        )
        
        # Step 2: Generate JSON output using the LLM.
        llm_output = generate_llm_response(prompt)
        logging.info(f"LLM Output generated.")
        
        # Step 3: Validate the generated JSON output.
        validated_data = validate_restaurant_json(llm_output)
        
        # Step 4: Handle the result.
        if validated_data:
            logging.info(f"Success: Validated JSON for '{validated_data.get('restaurant_name')}'")
            processed_restaurants.append(validated_data)
        else:
            logging.warning(f"Failed to process unstructured text: {raw_text[:30]}...")
            # Optionally implement retry logic here.
            
    # =====================================================================.
    
    return processed_restaurants

if __name__ == "__main__":
    # Sample unstructured data for the lab.
    unstructured_reviews = [
        "We went to Luigi's Trattoria last night. It's an Italian place. The pasta was amazing and I'd give it a 4.8 out of 5.",
        "Tokyo Sushi has the best sashimi in town. Rating is definitely a solid 5 stars. Highly recommended for Japanese food lovers.",
        "Burger Joint was okay. 3 stars. The fries were a bit cold, but the burgers are decent american fast food."
    ]
    
    # Run the loop.
    structured_data = process_unstructured_restaurant_data(unstructured_reviews)
    
    print("\n--- Final Structured Output ---")
    print(json.dumps(structured_data, indent=2))

